# Jekyll configuration
title: aleok
name: aleok's blog
remote_theme: alexdevteam/jekyll-dash
author: aleok
description: >
  Welcome. I'm aleok. I'm a robotics student and have been programming since I was a kid.
  This is my blog, where I like to put any ideas I find interesting.

plugins:
  - jekyll-remote-theme
  - jekyll-paginate

# jekyll-paginate
paginate: 5
paginate_path: "/blog/page:num/"

dash:
  # the way how dates should be displayed
  date_format: "%b %-d, %Y"

  # the animation speed of the post scroll-in effect
  animation_speed: 50

  # whether to enable Right-to-Left support or not
  rtl: false
  
  # whether the author box should be displayed or not
  show_author: true
